apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "ratings-page-jwt-okta-authn"
  namespace: default
spec:
  selector:
    matchLabels:
      app: ratings
  jwtRules:
  - issuer: "https://dev-2132729.okta.com/oauth2/aus3l2vo9tEJm5cZ35d7"
    jwksUri: "https://dev-2132729.okta.com/oauth2/aus3l2vo9tEJm5cZ35d7/v1/keys"
